ALTER TABLE public.profiles 
ADD COLUMN energy INTEGER DEFAULT 100,
ADD COLUMN xp_physical INTEGER DEFAULT 0,
ADD COLUMN xp_mental INTEGER DEFAULT 0,
ADD COLUMN xp_spiritual INTEGER DEFAULT 0,
ADD COLUMN xp_professional INTEGER DEFAULT 0,
ADD COLUMN xp_financial INTEGER DEFAULT 0;
